name: Create Release 
on:
  pull_request:
    types: [opened]
    branches: 
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Automatically approve and merge a Release PR
    if: "startsWith(github.event.head_commit.message, 'release:')"
    steps:
      # first checkout the code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Install java before installing clojure tools which needs java
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # Setup Clojure / Babashka environment
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: 1.11.1.1208             # Clojure CLI based on tools.deps
          bb: 1.1.172                  # Babashka
          clj-kondo: 2023.01.20        # Clj-kondo
          cljstyle: 0.15.0             # cljstyle
      # Use caching for fetched dependencies
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-
      # Approve the PR
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
      # Merge the PR
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          method: rebase # merge squash rebase
      # Create the actual release
      - name: create release
        run: |
          git fetch --all
          git checkout master
          git pull origin master
          bb release --only-release
        env:
          GITHUB_TOKEN: ${{ github.token }}